# -*- coding: utf-8 -*-
"""Task3_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MU0-Sr57pcnfP2ND2tjTPX5Newoq76gP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data
df = pd.read_csv("Task3.csv")

print("Shape:", df.shape)
df.info()
print("\nMissing values:\n", df.isnull().sum())
df.describe()

sns.histplot(df['price'])   # shows how many houses fall in each price range
plt.title("Price Distribution")
plt.show()

"""**Insight:** House prices are right-skewed — most properties fall between roughly 2M and 6M, with a smaller number of high-priced outliers stretching the distribution up to ~13M."""

sns.scatterplot(x=df['area'], y=df['price'])   # each dot = one house
plt.title("Area vs Price")
plt.show()

"""**Insight:** There is a clear positive relationship between area and price — larger properties tend to sell for more, though the relationship isn't perfectly linear, since some large properties are priced similarly to smaller ones."""

sns.boxplot(x=df['bedrooms'], y=df['price'])   # compares price across bedroom counts
plt.title("Bedrooms vs Price")
plt.show()

"""**Insight:** Median price rises from 1 to 5 bedrooms, but interestingly drops slightly for 6-bedroom homes — suggesting bedroom count alone doesn't fully explain price beyond a certain point."""

sns.boxplot(x=df['bathrooms'], y=df['price'])
plt.title("Bathrooms vs Price")
plt.show()

"""**Insight:** Bathrooms show a strong, consistent positive relationship with price — each additional bathroom tends to push the median price notably higher, more consistently than bedrooms do."""

sns.boxplot(x=df['airconditioning'], y=df['price'])
plt.title("AC vs Price")
plt.show()

"""**Insight:** Homes with air conditioning have a visibly higher median price than those without, making AC one of the stronger categorical price indicators in this dataset."""

sns.boxplot(x=df['furnishingstatus'], y=df['price'])
plt.title("Furnishing Status vs Price")
plt.show()

"""**Insight:** Furnished homes have the highest median price, followed by semi-furnished, then unfurnished — furnishing status has a smaller but still visible effect on price."""

sns.boxplot(x=df['mainroad'], y=df['price'])
plt.title("Main Road Access vs Price")
plt.show()

"""**Insight:** Homes with main road access have a higher median price than those without, likely reflecting the added convenience and accessibility buyers value."""

numeric_df = df.select_dtypes(include='number')   # keep only number columns
corr = numeric_df.corr()                          # calculate correlation between all of them

sns.heatmap(corr, annot=True, cmap='coolwarm')     # annot=True shows the numbers on the chart
plt.title("Correlation Heatmap")
plt.tight_layout()                                 # fixes squished/overlapping axis labels
plt.show()

"""**Insight:** Area (0.54) and bathrooms (0.52) have the strongest positive correlation with price, followed by stories (0.42), parking (0.38), and bedrooms (0.37) — confirming that size and bathroom count matter more to price than raw bedroom count.

## Conclusion

This EDA shows that price is primarily driven by property size (area) and bathroom count, with air conditioning, main road access, and furnishing status also contributing meaningful premiums. Price itself is right-skewed, meaning a small number of high-end properties pull the average above what a "typical" home costs — the median is a more representative figure. Bedroom count matters less than expected, plateauing (and even dipping) beyond 5 bedrooms, suggesting buyers value usable space and amenities over sheer room count.
"""

